### PR TITLE
#709 | wtlos balance incorrect after withdrawal unwrap

### LINKED ISSUE #709: WTLOS balance incorrect after withdrawal (unwrap)
**Describe the bug**

When an address withdraws (unwraps) WTLOS, the balance of TLOS is not updated on Teloscan. Additionally, the ERC20 transfer field is empty for the withdrawal transaction, even though it should contain the relevant information.

**To Reproduce**

1. Go to [this withdrawal transaction page](https://testnet.teloscan.io/tx/0xd895be51306468d9bbb920bd635fff2fff7e5ae73fcf2eafac108b43a1577e9c).

2. Note that the ERC20 transfer field is empty:
  
image

3. Click on the address and go to [this page](https://testnet.teloscan.io/address/0x1Da699A4fCCdD5Fb02562767C54b720DeC79212f?tab=tokens) to view the address balances. Note the incorrect TLOS balance.

4. Verify the user's WTLOS balance on the [WTLOS contract page](https://testnet.teloscan.io/address/0xaE85Bf723A9e74d6c663dd226996AC1b8d075AA9?tab=contract). Go to the "Read" tab, use the "balanceOf" method, and enter the address `0x1Da699A4fCCdD5Fb02562767C54b720DeC79212f`. The balance should be `2000000000000000000`.

**Expected behavior**

- The ERC20 transfer field should contain the relevant information for the WTLOS withdrawal transaction.
- The TLOS balance of the address should be updated on Teloscan after the withdrawal transaction.

**Actual behavior**

- The ERC20 transfer field is empty for the WTLOS withdrawal transaction.
- The TLOS balance of the address is not updated on Teloscan after the withdrawal transaction.

**Screenshots**
 ERC20 transfer field is empty:
  
image

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #709

## Description
This PR adds a new TLOS Section after the `to` field. It acts like the ERC transfers list but is based on internal transactions instead of logs.

## Test scenarios
- https://deploy-preview-714--testnet-teloscan.netlify.app/tx/0xd895be51306468d9bbb920bd635fff2fff7e5ae73fcf2eafac108b43a1577e9c

image

- https://deploy-preview-714--teloscan.netlify.app/tx/0x4ae128027a1d25d9883594f6bc84a276ef1c4b5c9e12d255372566a758e7aca2

image

- https://deploy-preview-714--teloscan.netlify.app/tx/0x0ecfd9b979c8d3412a3166470c5f8354781e6ff1f83157ec4b962c41d6fe1de3

image

### CODE REVIEW

File: src/boot/fathom.js [hunk 1]
```diff
@@ -1,16 +0,0 @@
...
-    // VMVLEWFD for mainnet
-    // HKAXCRJB for testnet
-    script.dataset.site = 'ISPYEAKT';
-    script.dataset.spa = 'auto';
-    script.defer = true;
-    document.body.appendChild(script);
-
-    console.log('Fathom installed !!!'); // FIXME: remove this line
-});
-
```
Comment (Viterbo) [inline src/boot/fathom.js:16]: IDK why this is here. This is what I wrote for OBE but it seems I created here by mistake and forgot to remove it. So I'm doing it now.

**Review by pmjanus — APPROVED** [review]
