### PR TITLE
#983 | Fix for the inconsistency on the website showing a contract as "verified" and "not verified" at the same time.

### LINKED ISSUE #983: Fix wTLOS Verification Status Display on Teloscan UI / Indexer
**Fixed here:** https://github.com/telosnetwork/teloscan/pull/992

### [Bug] 

🐛 **Description**
The verification status for wTLOS is not displaying correctly on the Teloscan interface. This needs to be investigated and fixed to ensure accurate contract verification information is shown to users.

📋 **Current Behavior**
- wTLOS verification status is not showing correctly on Teloscan Indexer
- Issue appears to be specific to wTLOS contract

🔍 **Investigation Points**
- [ ] Verify if this is isolated to wTLOS or affects other wrapped tokens
- [ ] Check verification status in backend database
- [ ] Inspect API response for verification status
- [ ] Review frontend display logic for verification badges

✅ **Tasks**
- [ ] Investigate root cause of verification display issue
- [ ] Fix verification status retrieval/display logic
- [ ] Add verification status check to test suite
- [ ] Deploy fix to staging environment
- [ ] Verify fix in production

⚡ **Impact**
- Users unable to confirm wTLOS contract verification status
- May affect trust and transparency of wrapped token contracts

🏷️ **Labels**
`bug` `frontend` `verification` `wrapped-tokens`

💻 **Environment**
- Production environment
- Affects Teloscan Indexer interface

📝 **Notes**
- This appears to be a display issue rather than an actual verification problem
- Should be treated as high priority due to impact on user trust
- 

Image

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #983

## Description
This PR fixes the problem of showing a contract as verified and not verified at the same time.

Unfortunately, I verified the only contract that we know is causing this problem. But I found a way of replicating the previous situation of that contract to test the PR fix following the next steps:

## Test Steps
- open the contract on the PR deployment:
https://deploy-preview-992--testnet-teloscan.netlify.app/address/0xaE85Bf723A9e74d6c663dd226996AC1b8d075AA9?tab=contract&subtab=source
- open the same contract on the current production deployment:
https://testnet.teloscan.io/address/0xaE85Bf723A9e74d6c663dd226996AC1b8d075AA9?tab=contract&subtab=source
- open the developer tools in the Network tab and refresh both pages.
- you will notice there's a fetch for a source.json file (/0xaE85Bf723A9e74d6c663dd226996AC1b8d075AA9/source.json)
- You need to block that file from being fetched. Right-click over the source.json and click on "Block request URL" (see image below)
image
- You should see some filter like in the image
image
- Finally, refresh both pages (the PR deployment and the Testnet production deployment)
- on the PR deployment you should get a not verified contract banner like in the image
image
- and on the production Testnet deployment you will still get the inconsistency double message (verified and not verified at the same time). See the image:
image

### CODE REVIEW

File: src/pages/AccountPage.vue [hunk 1]
```diff
@@ -120,7 +121,7 @@ async function loadAccount() {
                     contract.value.issuer = token.issuer;
                     contract.value.issuer_link = token.issuer_link;
                     contract.value.logoURI = token.logoURI;
-                    contract.value.setVerified(true);
+                    // contract.value.setVerified(true); // FIXME
```
Comment (pmjanus) [inline src/pages/AccountPage.vue:124]: Cleanup

Comment (Viterbo) [reply src/pages/AccountPage.vue]: cleaned and conflict solved
