### PR TITLE
Transaction status icon

### LINKED ISSUE #590: Add Information Icon to identify Failed txns and txns with a reversal
Some txns will fail and need to be id with a Red information icon, the icon should have a tooltip that says:
Txn Failed
Some will have partial execution and need to be id with a yellow information icon, the icon tooltip:
One or more errors in the contract execution.

### PR DESCRIPTION
**Pull request by donnyquixotic**
Fixes #590 #604 

Additional Fixes:

- `load_error` i18n references corrected
- horizontal scroll styling on tx table
- QR code units to maintain width on different screen resolutions

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [x] I have added appropriate test coverage
-   [x] I have updated relevant documentation and/or opened a separate issue to cover the updates (Issue URL: )

### CODE REVIEW

File: src/components/TransactionTable.vue [hunk 1]
```diff
@@ -464,6 +465,11 @@ function getValueDisplay(value: string) {
     }
 }
 
+// quasar override
+.q-table__middle{
+    @include scroll-bar;
+}
+
```
Comment (Viterbo) [inline src/components/TransactionTable.vue:472]: Can you move this style to the end of the file src/css/app.scss ?
We already have some quasar overrides there. It would be nice to have them all there in the same place.

File: src/i18n/es-es/index.js [hunk 2]
```diff
@@ -242,6 +242,7 @@ export default {
         to_interacted_with: 'A',
         value: 'Valor',
         txn_fee: 'Txn Fee',
+        txn_failed: 'Txn Fallido',
```
Comment (Viterbo) [inline src/i18n/es-es/index.js:245]: In Spanish, we have gendered nouns. "La transacción" is feminine, but the adjective "fallido" is used to match the masculine noun, so you need to use "fallida".

```suggestion
        txn_failed: 'Txn Fallida',
```

**Review by Viterbo — CHANGES_REQUESTED** [review]
Good job!
I notice there is some commented code in the file src/pages/AccountPage.vue
Is it temporal? Can it be removed?

**Review by rozzaswap — APPROVED** [review]
