### PR TITLE
#252 | Fix iOS staking inputs bug

### LINKED ISSUE #252: Can't stake using metamask browser on iOS
## Overview

On Teloscan staking, entering an amount on the top TLOS field was moving my cursor to the end of the bottom sTLOS field before I was done entering the amount I wanted in the TLOS field

iOS, all browsers

Additionally, there is no way to enter decimals as there is no `.` on the iOS numpad

## Steps to reproduce

1. User your metamask to access teloscan website
2. Connect your wallet
3. Go to stake Telos
4. Select the first input field

## Current behavior

You're unable to type the TLOS

## Expected behavior

User should be able to type the number of TLOS they would like to stake
User should be able to see the number of sTLOS they'll receive for the specified quantity of TLOS
User should be able to enter fractional amounts

### PR DESCRIPTION
**Pull request by EJSG**
# Fixes #252

## Description
This is a workaround for a bug where, on iOS devices, entering a value into one staking input causes the other input to be focused. This is due to the system (iOS behavior) incorrectly focusing an input if its value is changed programmatically. 

Additionally on iOS devices, no `.` is shown on the keyboard, making it impossible to enter fractional values. This is also fixed in this PR.

## Test scenarios
- on an iOS device, go to the deploy preview, https://deploy-preview-267--benevolent-tapioca-f74277.netlify.app/
- for each input (Stake tab top and bottom, Unstake tab top and bottom), enter a value
    - you should see the other input enter a loading state, then show a value
    - the input you were on should not lose focus
    - the numpad keyboard should show a period `.`

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

### CODE REVIEW

**Review by donnyquixotic — APPROVED** [review]

File: src/pages/staking/StakeForm.vue [hunk 1]
```diff
@@ -271,8 +271,19 @@ export default {
...
+                        if (getClientIsApple()) {
+                            // workaround; Apple devices will focus the last input which had its value
+                            // programmatically changed. Focus should not change. Downside is that cursor position
+                            // is lost, but generally cursor should be at the end anyway
+                            const old = this.topInputAmount;
+                            this.topInputAmount = '0';
+                            await this.$nextTick();
+
+                            this.topInputAmount = old;
+                        }
```
Comment (karynemayer) [inline src/pages/staking/StakeForm.vue:286]: Could we turn `this.topInputAmount` and `this.bottomInputAmount` into parameters and reuse the function? I think there are 4 places we could use such a function

**Review by karynemayer — CHANGES_REQUESTED** [review]

**Comment by karynemayer** [comment]
@EJSG Also, I'm unable to stake a number that is a fraction. I can see a comma on my keyboard, but I can't create a fraction value with it. I can only send a fraction by typing a big value and editing my whole balance.

image

**Comment by EJSG** [comment]
@karynemayer what device and browser are you on?

File: src/pages/staking/StakeForm.vue (hunk 1 above)
Comment (EJSG) [reply src/pages/staking/StakeForm.vue:286]: these functions rely on the `this` context and also differ slightly each time (depending on whether it needs top or bottom input), i dont think it'll be worth refactoring because of that complexity

**Comment by karynemayer** [comment]
@EJSG iOS 16.2 and MetaMask v5.12.3 (1033)

**Review by karynemayer — APPROVED** [review]
After talking to @EJSG, the root cause was identified and https://github.com/telosnetwork/teloscan/issues/279 was created to reflect it
