### PR TITLE
#892 | fixing icon-balance row

### LINKED ISSUE #892: bug | broken line in the info card on Address page
**Describe the bug**
A break line is present in the first info card on the address page. You can see three lines with the icon alone in the middle when the icon should be in the same balance line.

**To Reproduce**
1. Go to any [address page](https://www.teloscan.io/address/0x1E189D0955561589fb891B38d2b0762d9C60853B)
4. See three lines with the icon alone in the middle when there should be only two lines

image

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #892

## Description
The balance line was displayed as a column, making the icon and balance text aligned vertically instead of horizontally. This PR fixes that and also makes a forgotten hard-coded TLOS symbol to be dynamic, depending on the selected network.

## Test scenarios

https://deploy-preview-894--dev-mainnet-teloscan.netlify.app/address/0x45cB7B68F22A8CeD95305e21F451BFD0f499242e?network=telos-evm

image

### CODE REVIEW

**Review by pmjanus — APPROVED** [review]

File: src/components/AddressOverview.vue [hunk 1]
```diff
@@ -34,11 +34,11 @@ const systemToken = useChainStore().currentChain.settings.getSystemToken();
         <q-skeleton type="text" class="c-address-overview__skeleton" />
     </q-card-section>
     <q-card-section v-else>
-        <div class="c-address-overview__label"> TLOS {{ $t('pages.balance') }} </div>
+        <div class="c-address-overview__label"> {{ systemToken.symbol }} {{ $t('pages.balance') }} </div>
         <div class="c-address-overview__balance">
             <img
```
Comment (pmjanus) [inline src/components/AddressOverview.vue:39]: image
Can we fix logo placement (align it to the balance value).

Comment (Viterbo) [reply src/components/AddressOverview.vue:39]: I see it normally

image

What browser are you using?

Comment (pmjanus) [reply src/components/AddressOverview.vue:39]: I use chrome

Comment (pmjanus) [reply src/components/AddressOverview.vue:39]: can't reproduce it, weird.
