### PR TITLE
Transactions table & Menu link fixes

### LINKED ISSUE #189: Fix addresses showing up as contracts on account and transactions pages
From Jesse on Telegram:

> https://www.teloscan.io/address/0x0e79065B5F11b5BD1e62B935A600976ffF3754B9
> Looking at that address, it shows every To address is a contract, but when you click on the To addresses they aren't contracts.

I also noticed this sometimes happens on the main transactions page, but not with all addresses so not entirely sure if it is the same issue or not.

### PR DESCRIPTION
**Pull request by tomtomcrypto**
# Fixes #189  & #191

## Description

#189: The to addresses on transactions table (account page & transactions page) had several problems, including: being tagged as contract when they shouldn't, not loading the name on navigation, etc....

#191: The menu links for mainnet / testnet were wrong

## Test scenarios

Checked different account & transactions pages to make sure the to addresses showed correctly

Checked the menu on testnet & mainnet to make sure the correction worked

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

### CODE REVIEW

File: src/layouts/MainLayout.vue [hunk 1]
```diff
@@ -130,7 +130,7 @@ export default {
     },
     data() {
         return {
-            mainnet: process.env.NETWORK_EVM_CHAIN_ID === '40',
+            mainnet: '' + process.env.NETWORK_EVM_CHAIN_ID + '' === '40',
```
Comment (donnyquixotic) [inline src/layouts/MainLayout.vue:133]: prepending/appending necessary?

**Review by donnyquixotic — CHANGES_REQUESTED** [review]
