### PR TITLE
block route redesign - fixes

### LINKED ISSUE #534: Block route redesign
the `/block` route should be refactored to show the following information _instead of_ a table of transactions:

- block height
    - tooltip: `Also called "Block Number". The block height represents the length of of the blockchain, increasing by one after the addition of a new block`
- timestamp
    - tooltip: "The time and date the block was produced"
    - in the format of `[clock icon] X unit ago (Mmm-DD-YYYY HH:MM:SS AM/PM +UTC)` e.g. `9 mins ago (Feb-16-2024 10:06:23 PM +UTC)`
- transactions
    -tooltip: "The number of transactions in the block. Internal Transactions are transactions which occur as a result of contract execution and include a TLOS value"
    - in the format of `X transactions and Y contract internal transactions in this block`, where "X transactions" is clickable and leads to `/txs?block={blocknum}`
- size
    - tooltip: "the amount of data in the block, determined by the gas limit"
    - `X bytes` where X is the size of the block, formatted using `toLocaleString()`
- gas used
    - tooltip: "The amount of gas used in the block"
    - show gas used, formatted using `toLocaleString()`
- gas limit
    - tooltip: "The gas limit for all transactions in the block"
    - show gas limit, formatted using `toLocaleString()`
- nonce
    - tooltip: "The value used during mining to achieve consensus on Proof of Work for the block"
    - show nonce
- hash
    - tooltip: "The hash of the block header"
    - show hash
- parent hash
    - tooltip: "The hash of the parent block"
    - show hash

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #534

## Description
The original branch was already merged so I created this new one for a new PR with the remaining fixes.
- show transacxtionsRoot field
- click on extra data redirect to a non hard-coded explorer. Now is taken from the envs
- fields reordered

## Screenshots

image

### CODE REVIEW

**Review by donnyquixotic — APPROVED** [review]

**Review by pmjanus — APPROVED** [review]

File: src/pages/BlockPage.vue [hunk 1]
```diff
@@ -46,6 +46,7 @@ const loadBlockData = async () => {
         }
         const response = await indexerApi.get(`/block/${blockHeight.value}`);
         blockData.value = toRaw(response.data?.results?.[0]) as BlockData;
+        console.log('blockData.value', blockData.value);
```
Comment (donnyquixotic) [inline src/pages/BlockPage.vue:49]:
```suggestion
```

**Review by donnyquixotic — APPROVED** [review]

**Review by donnyquixotic — APPROVED** [review]
